In [1]:
import fastf1
import pandas as pd

In [10]:
session = fastf1.get_session(2025, 10, 'R')

session.load()

core           INFO 	Loading data for Canadian Grand Prix - Race [v3.5.3]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...

logger      WARNING 	Failed to load session info data!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
core        WARNING 	Failed to load extended driver information!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
core        WARNING 	Failed to load driver list and session results!
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
logger      WARNING 	Failed to load session status data!
req            INFO 	No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
logger      WARNING 	Failed to load total lap count!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
logger      WARNING 	Failed to load track status data!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
logger      WARNING 	Failed to load timing data!
core        WARNING 	Cannot load lap times for first lap from Ergast. Timing data is not available for this session.
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
core        WARNING 	Car telemetry data is unavailable!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
core        WARNING 	Car position data is unavailable!
core        WARNING 	Failed to determine `Session.t0_date`!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
logger      WARNING 	Failed to load weather data!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
logger      WARNING 	Failed to load race control messages!
core           INFO 	Finished loading data for 0 drivers: []

In [3]:
session.event["OfficialEventName"]

'FORMULA 1 PIRELLI GRAND PRIX DU CANADA 2025'

In [4]:
session.results

Empty DataFrame
Columns: [DriverNumber, BroadcastName, Abbreviation, DriverId, TeamName, TeamColor, TeamId, FirstName, LastName, FullName, HeadshotUrl, CountryCode, Position, ClassifiedPosition, GridPosition, Q1, Q2, Q3, Time, Status, Points]
Index: []

[0 rows x 21 columns]

In [40]:
session.results.dtypes

DriverNumber                   object
BroadcastName                  object
Abbreviation                   object
DriverId                       object
TeamName                       object
TeamColor                      object
TeamId                         object
FirstName                      object
LastName                       object
FullName                       object
HeadshotUrl                    object
CountryCode                    object
Position                      float64
ClassifiedPosition             object
GridPosition                  float64
Q1                    timedelta64[ns]
Q2                    timedelta64[ns]
Q3                    timedelta64[ns]
Time                  timedelta64[ns]
Status                         object
Points                        float64
dtype: object

In [45]:
session.laps

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,FreshTyre,Team,LapStartTime,LapStartDate,TrackStatus,Position,Deleted,DeletedReason,FastF1Generated,IsAccurate
0,0 days 01:04:01.390000,GAS,10,0 days 00:01:39.330000,1.0,1.0,NaT,NaT,NaT,0 days 00:00:39.238000,...,True,AlphaTauri,0 days 01:02:21.871000,2021-12-12 13:03:21.881,1,12.0,False,,False,False
1,0 days 01:05:34.204000,GAS,10,0 days 00:01:32.814000,2.0,1.0,NaT,NaT,0 days 00:00:18.899000,0 days 00:00:38.961000,...,True,AlphaTauri,0 days 01:04:01.390000,2021-12-12 13:05:01.400,1,12.0,False,,False,True
2,0 days 01:07:05.737000,GAS,10,0 days 00:01:31.533000,3.0,1.0,NaT,NaT,0 days 00:00:18.581000,0 days 00:00:38.489000,...,True,AlphaTauri,0 days 01:05:34.204000,2021-12-12 13:06:34.214,1,12.0,False,,False,True
3,0 days 01:08:37.176000,GAS,10,0 days 00:01:31.439000,4.0,1.0,NaT,NaT,0 days 00:00:18.507000,0 days 00:00:38.592000,...,True,AlphaTauri,0 days 01:07:05.737000,2021-12-12 13:08:05.747,1,12.0,False,,False,True
4,0 days 01:10:08.543000,GAS,10,0 days 00:01:31.367000,5.0,1.0,NaT,NaT,0 days 00:00:18.400000,0 days 00:00:38.837000,...,True,AlphaTauri,0 days 01:08:37.176000,2021-12-12 13:09:37.186,1,12.0,False,,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0 days 01:48:13.815000,GIO,99,0 days 00:01:29.775000,30.0,2.0,NaT,NaT,0 days 00:00:18.146000,0 days 00:00:38.496000,...,True,Alfa Romeo Racing,0 days 01:46:44.040000,2021-12-12 13:47:44.050,1,13.0,False,,False,True
996,0 days 01:49:43.320000,GIO,99,0 days 00:01:29.505000,31.0,2.0,NaT,NaT,0 days 00:00:18.093000,0 days 00:00:38.532000,...,True,Alfa Romeo Racing,0 days 01:48:13.815000,2021-12-12 13:49:13.825,1,13.0,False,,False,True
997,0 days 01:51:12.916000,GIO,99,0 days 00:01:29.596000,32.0,2.0,NaT,NaT,0 days 00:00:18.098000,0 days 00:00:38.526000,...,True,Alfa Romeo Racing,0 days 01:49:43.320000,2021-12-12 13:50:43.330,1,13.0,False,,False,True
998,0 days 01:52:42.358000,GIO,99,0 days 00:01:29.442000,33.0,2.0,NaT,NaT,0 days 00:00:17.989000,0 days 00:00:38.608000,...,True,Alfa Romeo Racing,0 days 01:51:12.916000,2021-12-12 13:52:12.926,1,13.0,False,,False,True
999,0 days 01:54:12.993000,GIO,99,NaT,34.0,2.0,NaT,NaT,NaT,NaT,...,True,Alfa Romeo Racing,0 days 01:52:42.358000,NaT,1,NaN,False,NaN,True,False

In [9]:
driver_stats = []


for result in session.results.iterrows():
    driver = result[1]["Abbreviation"]
    
    avg_lap_time = session.laps.pick_drivers(driver)["LapTime"].mean()
    
    driver_stats.append({
        "Driver": result[1]["Abbreviation"],
        "TeamId": result[1]["TeamId"],
        "FinishPosition": result[1]["Position"],
        "PositionsGained": result[1]["Position"] - result[1]["GridPosition"],
        "PointsGained": result[1]["Points"],
        "AvgLapTime": avg_lap_time,
    })
    
driver_stats_df = pd.DataFrame(driver_stats)

driver_stats_df

,Driver,TeamId,FinishPosition,PositionsGained,PointsGained,AvgLapTime
0,PIA,mclaren,1.0,-3.0,25.0,0 days 00:01:33.536614035
1,NOR,mclaren,2.0,0.0,18.0,0 days 00:01:33.617842105
2,RUS,mercedes,3.0,-2.0,15.0,0 days 00:01:34.197035087
3,VER,red_bull,4.0,3.0,12.0,0 days 00:01:34.237596491
4,ALB,williams,5.0,-2.0,10.0,0 days 00:01:34.379894736
5,ANT,mercedes,6.0,3.0,8.0,0 days 00:01:34.510333333
6,LEC,ferrari,7.0,-1.0,6.0,0 days 00:01:34.537245614
7,HAM,ferrari,8.0,-4.0,4.0,0 days 00:01:34.592508771
8,SAI,williams,9.0,3.0,2.0,0 days 00:01:34.599368421
9,TSU,red_bull,10.0,0.0,1.0,0 days 00:01:34.754754385
10,HAD,rb,11.0,0.0,0.0,0 days 00:01:34.845421052
11,OCO,haas,12.0,3.0,0.0,0 days 00:01:34.975315789
12,GAS,alpine,13.0,-7.0,0.0,0 days 00:01:35.123368421
13,HUL,sauber,14.0,-2.0,0.0,0 days 00:01:35.227535714
14,ALO,aston_martin,15.0,-2.0,0.0,0 days 00:01:35.581535714
15,STR,aston_martin,16.0,-2.0,0.0,0 days 00:01:35.656232142
16,LAW,rb,17.0,2.0,0.0,0 days 00:01:38.514194444
17,BOR,sauber,18.0,5.0,0.0,0 days 00:01:38.115300
18,BEA,haas,19.0,0.0,0.0,0 days 00:01:35.954555555
19,DOO,alpine,20.0,6.0,0.0,NaT

In [71]:
driver_stats_df = driver_stats_df.dropna()

driver_stats_df

,Driver,TeamId,FinishPosition,PositionsGained,PointsGained,AvgLapTime
0,VER,red_bull,1.0,0.0,26.0,0 days 00:01:32.401929824
1,HAM,mercedes,2.0,0.0,18.0,0 days 00:01:32.412596491
2,SAI,ferrari,3.0,-2.0,15.0,0 days 00:01:33.491689655
3,TSU,alphatauri,4.0,-4.0,12.0,0 days 00:01:33.500637931
4,GAS,alphatauri,5.0,-7.0,10.0,0 days 00:01:33.515103448
5,BOT,mercedes,6.0,0.0,8.0,0 days 00:01:33.531172413
6,NOR,mclaren,7.0,4.0,6.0,0 days 00:01:33.410614035
7,ALO,alpine,8.0,-3.0,4.0,0 days 00:01:33.456719298
8,OCO,alpine,9.0,0.0,2.0,0 days 00:01:33.505736842
9,LEC,ferrari,10.0,3.0,1.0,0 days 00:01:33.538859649
10,VET,aston_martin,11.0,-4.0,0.0,0 days 00:01:33.585052631
11,RIC,mclaren,12.0,2.0,0.0,0 days 00:01:34.114250
12,STR,aston_martin,13.0,0.0,0.0,0 days 00:01:35.181175438
13,MSC,haas,14.0,-5.0,0.0,0 days 00:01:35.192052631
14,PER,red_bull,15.0,11.0,0.0,0 days 00:01:31.864927272
15,LAT,williams,16.0,0.0,0.0,0 days 00:01:32.309820
16,GIO,alfa,17.0,3.0,0.0,0 days 00:01:31.524181818
17,RUS,williams,18.0,1.0,0.0,0 days 00:01:32.183720
18,RAI,alfa,19.0,1.0,0.0,0 days 00:01:34.544440